Update tests

diff --git a/.github/workflows/test_client.yaml b/.github/workflows/test_client.yaml
--- a/.github/workflows/test_client.yaml
+++ b/.github/workflows/test_client.yaml
@@ -109,6 +109,13 @@ jobs:
           ./client/test_utils/certification_emulator.py error 8004 &
           ./client/test_utils/certification_emulator.py error-data 8005 &
           sleep 2
+          if snap run hwctl --origin server --server http://localhost:8000 ; then
+            echo "hwctl didn't return an error when the server returned an error"
+            exit 1
+          else
+            echo "hwctl failed, as expected, when the server returned an error"
+          fi
+          sudo snap set hwctl allow-custom-url=true
           snap run hwctl --origin server --server http://localhost:8000 |jq .status | grep '"Certified"'
           snap run hwctl --origin server --server http://localhost:8001 |jq .status | grep '"NotSeen"'
           snap run hwctl --origin server --server http://localhost:8002 |jq .status | grep '"CertifiedImageExists"'
